// Credit: Palettes from [kgolid's chromotome](https://github.com/kgolid/chromotome)
// via [https://nice-colours-quicker.netlify.app/](nice-colours-quicker)
export const palettes = [
    {
        name: "neill-rybitten1",
        colors: ["#906593", "#DE2C26", "#F2B47F", "#F6D3CA", "#B8D7BE"],
        stroke: 20,
        background: 20,
        size: 5,
        type: "chromotome",
    },
    {
        name: "nowak",
        colors: [
            "#e85b30",
            "#ef9e28",
            "#c6ac71",
            "#e0c191",
            "#3f6279",
            "#ee854e",
            "#180305",
        ],
        stroke: "#180305",
        background: "#ede4cb",
        size: 7,
        type: "chromotome",
    },
    {
        name: "system.#04",
        colors: [
            "#e31f4f",
            "#f0ac3f",
            "#18acab",
            "#26265a",
            "#ea7d81",
            "#dcd9d0",
        ],
        stroke: "#26265a",
        backgrund: "#dcd9d0",
        size: 6,
        type: "chromotome",
    },

    {
        name: "tsu_arcade",
        colors: [
            "#4aad8b",
            "#e15147",
            "#f3b551",
            "#cec8b8",
            "#d1af84",
            "#544e47",
        ],
        stroke: "#251c12",
        background: "#cfc7b9",
        size: 6,
        type: "chromotome",
    },
    {
        name: "giftcard_sub",
        colors: [
            "#FBF5E9",
            "#FF514E",
            "#FDBC2E",
            "#4561CC",
            "#2A303E",
            "#6CC283",
            "#238DA5",
            "#9BD7CB",
        ],
        stroke: "#000",
        background: "#FBF5E9",
        size: 8,
        type: "chromotome",
    },
    {
        name: "revolucion",
        colors: ["#ed555d", "#fffcc9", "#41b797", "#eda126", "#7b5770"],
        stroke: "#fffcc9",
        background: "#2d1922",
        size: 5,
        type: "chromotome",
    },
];
